[2023-05-06T09:37:16.646+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_to_gcs.hello_world scheduled__2023-05-05T00:00:00+00:00 [queued]>
[2023-05-06T09:37:16.657+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_to_gcs.hello_world scheduled__2023-05-05T00:00:00+00:00 [queued]>
[2023-05-06T09:37:16.657+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-06T09:37:16.677+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): hello_world> on 2023-05-05 00:00:00+00:00
[2023-05-06T09:37:16.683+0000] {standard_task_runner.py:57} INFO - Started process 122 to run task
[2023-05-06T09:37:16.686+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'upload_to_gcs', 'hello_world', 'scheduled__2023-05-05T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/upload_to_gcs.py', '--cfg-path', '/tmp/tmpif677z66']
[2023-05-06T09:37:16.688+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask hello_world
[2023-05-06T09:37:16.736+0000] {task_command.py:410} INFO - Running <TaskInstance: upload_to_gcs.hello_world scheduled__2023-05-05T00:00:00+00:00 [running]> on host c32461df29f3
[2023-05-06T09:37:16.828+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_to_gcs' AIRFLOW_CTX_TASK_ID='hello_world' AIRFLOW_CTX_EXECUTION_DATE='2023-05-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-05T00:00:00+00:00'
[2023-05-06T09:37:16.830+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/upload_to_gcs.py", line 31, in hello
    logging('Hello world')
TypeError: 'module' object is not callable
[2023-05-06T09:37:16.837+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_to_gcs, task_id=hello_world, execution_date=20230505T000000, start_date=20230506T093716, end_date=20230506T093716
[2023-05-06T09:37:16.849+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 7 for task hello_world ('module' object is not callable; 122)
[2023-05-06T09:37:16.897+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-06T09:37:16.946+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
