[2023-06-15T14:09:40.891+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_2_bq_dag.bq_2019_tripdata_external_table_task scheduled__2023-06-14T00:00:00+00:00 [queued]>
[2023-06-15T14:09:40.903+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_2_bq_dag.bq_2019_tripdata_external_table_task scheduled__2023-06-14T00:00:00+00:00 [queued]>
[2023-06-15T14:09:40.903+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-15T14:09:40.918+0000] {taskinstance.py:1327} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bq_2019_tripdata_external_table_task> on 2023-06-14 00:00:00+00:00
[2023-06-15T14:09:40.924+0000] {standard_task_runner.py:57} INFO - Started process 58 to run task
[2023-06-15T14:09:40.928+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'bq_2019_tripdata_external_table_task', 'scheduled__2023-06-14T00:00:00+00:00', '--job-id', '472', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq.py', '--cfg-path', '/tmp/tmpv3ytkcds']
[2023-06-15T14:09:40.930+0000] {standard_task_runner.py:85} INFO - Job 472: Subtask bq_2019_tripdata_external_table_task
[2023-06-15T14:09:40.976+0000] {task_command.py:410} INFO - Running <TaskInstance: gcs_2_bq_dag.bq_2019_tripdata_external_table_task scheduled__2023-06-14T00:00:00+00:00 [running]> on host 659e337ed365
[2023-06-15T14:09:41.068+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_2_bq_dag' AIRFLOW_CTX_TASK_ID='bq_2019_tripdata_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-14T00:00:00+00:00'
[2023-06-15T14:09:41.085+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1606, in execute
    bq_hook = BigQueryHook(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 105, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/common/hooks/base_google.py", line 234, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2023-06-15T14:09:41.090+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_2_bq_dag, task_id=bq_2019_tripdata_external_table_task, execution_date=20230614T000000, start_date=20230615T140940, end_date=20230615T140941
[2023-06-15T14:09:41.104+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 472 for task bq_2019_tripdata_external_table_task (The conn_id `google_cloud_default` isn't defined; 58)
[2023-06-15T14:09:41.139+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T14:09:41.155+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-15T15:21:32.364+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_2_bq_dag.bq_2019_tripdata_external_table_task scheduled__2023-06-14T00:00:00+00:00 [queued]>
[2023-06-15T15:21:32.376+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_2_bq_dag.bq_2019_tripdata_external_table_task scheduled__2023-06-14T00:00:00+00:00 [queued]>
[2023-06-15T15:21:32.377+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-15T15:21:32.389+0000] {taskinstance.py:1327} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bq_2019_tripdata_external_table_task> on 2023-06-14 00:00:00+00:00
[2023-06-15T15:21:32.395+0000] {standard_task_runner.py:57} INFO - Started process 1058 to run task
[2023-06-15T15:21:32.398+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'bq_2019_tripdata_external_table_task', 'scheduled__2023-06-14T00:00:00+00:00', '--job-id', '490', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq.py', '--cfg-path', '/tmp/tmpceazyvsq']
[2023-06-15T15:21:32.401+0000] {standard_task_runner.py:85} INFO - Job 490: Subtask bq_2019_tripdata_external_table_task
[2023-06-15T15:21:32.456+0000] {task_command.py:410} INFO - Running <TaskInstance: gcs_2_bq_dag.bq_2019_tripdata_external_table_task scheduled__2023-06-14T00:00:00+00:00 [running]> on host 659e337ed365
[2023-06-15T15:21:32.530+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_2_bq_dag' AIRFLOW_CTX_TASK_ID='bq_2019_tripdata_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-14T00:00:00+00:00'
[2023-06-15T15:21:32.549+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1606, in execute
    bq_hook = BigQueryHook(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 105, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/common/hooks/base_google.py", line 234, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2023-06-15T15:21:32.554+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_2_bq_dag, task_id=bq_2019_tripdata_external_table_task, execution_date=20230614T000000, start_date=20230615T152132, end_date=20230615T152132
[2023-06-15T15:21:32.564+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 490 for task bq_2019_tripdata_external_table_task (The conn_id `google_cloud_default` isn't defined; 1058)
[2023-06-15T15:21:32.609+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T15:21:32.637+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-15T16:15:37.764+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_2_bq_dag.bq_2019_tripdata_external_table_task scheduled__2023-06-14T00:00:00+00:00 [queued]>
[2023-06-15T16:15:37.782+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_2_bq_dag.bq_2019_tripdata_external_table_task scheduled__2023-06-14T00:00:00+00:00 [queued]>
[2023-06-15T16:15:37.783+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-15T16:15:37.807+0000] {taskinstance.py:1327} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bq_2019_tripdata_external_table_task> on 2023-06-14 00:00:00+00:00
[2023-06-15T16:15:37.818+0000] {standard_task_runner.py:57} INFO - Started process 1851 to run task
[2023-06-15T16:15:37.826+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'bq_2019_tripdata_external_table_task', 'scheduled__2023-06-14T00:00:00+00:00', '--job-id', '512', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq.py', '--cfg-path', '/tmp/tmp2xke1r2p']
[2023-06-15T16:15:37.830+0000] {standard_task_runner.py:85} INFO - Job 512: Subtask bq_2019_tripdata_external_table_task
[2023-06-15T16:15:37.906+0000] {task_command.py:410} INFO - Running <TaskInstance: gcs_2_bq_dag.bq_2019_tripdata_external_table_task scheduled__2023-06-14T00:00:00+00:00 [running]> on host 659e337ed365
[2023-06-15T16:15:38.047+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_2_bq_dag' AIRFLOW_CTX_TASK_ID='bq_2019_tripdata_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-14T00:00:00+00:00'
[2023-06-15T16:15:38.071+0000] {base.py:73} INFO - Using connection ID 'gcloud' for task execution.
[2023-06-15T16:15:39.996+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=gcs_2_bq_dag, task_id=bq_2019_tripdata_external_table_task, execution_date=20230614T000000, start_date=20230615T161537, end_date=20230615T161539
[2023-06-15T16:15:40.045+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-15T16:15:40.072+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
