[2023-06-15T15:39:10.300+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: add_gcp_connection.add_gcp_connection_python scheduled__2023-06-14T00:00:00+00:00 [queued]>
[2023-06-15T15:39:10.307+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: add_gcp_connection.add_gcp_connection_python scheduled__2023-06-14T00:00:00+00:00 [queued]>
[2023-06-15T15:39:10.308+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-15T15:39:10.331+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): add_gcp_connection_python> on 2023-06-14 00:00:00+00:00
[2023-06-15T15:39:10.340+0000] {standard_task_runner.py:57} INFO - Started process 1318 to run task
[2023-06-15T15:39:10.343+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'add_gcp_connection', 'add_gcp_connection_python', 'scheduled__2023-06-14T00:00:00+00:00', '--job-id', '497', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq.py', '--cfg-path', '/tmp/tmpevw9e4ba']
[2023-06-15T15:39:10.345+0000] {standard_task_runner.py:85} INFO - Job 497: Subtask add_gcp_connection_python
[2023-06-15T15:39:10.385+0000] {task_command.py:410} INFO - Running <TaskInstance: add_gcp_connection.add_gcp_connection_python scheduled__2023-06-14T00:00:00+00:00 [running]> on host 659e337ed365
[2023-06-15T15:39:10.444+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='add_gcp_connection' AIRFLOW_CTX_TASK_ID='add_gcp_connection_python' AIRFLOW_CTX_EXECUTION_DATE='2023-06-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-14T00:00:00+00:00'
[2023-06-15T15:39:10.445+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/gcs_to_bq.py", line 26, in add_gcp_connection
    conn_id=get_default_google_cloud_connection_id(),
NameError: name 'get_default_google_cloud_connection_id' is not defined
[2023-06-15T15:39:10.453+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=add_gcp_connection, task_id=add_gcp_connection_python, execution_date=20230614T000000, start_date=20230615T153910, end_date=20230615T153910
[2023-06-15T15:39:10.463+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 497 for task add_gcp_connection_python (name 'get_default_google_cloud_connection_id' is not defined; 1318)
[2023-06-15T15:39:10.474+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T15:39:10.486+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
