[2023-06-15T15:18:26.122+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_2_bq_dag.bq_2020_tripdata_external_table_task manual__2023-06-15T15:18:23.800047+00:00 [queued]>
[2023-06-15T15:18:26.139+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_2_bq_dag.bq_2020_tripdata_external_table_task manual__2023-06-15T15:18:23.800047+00:00 [queued]>
[2023-06-15T15:18:26.140+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-06-15T15:18:26.158+0000] {taskinstance.py:1327} INFO - Executing <Task(BigQueryCreateExternalTableOperator): bq_2020_tripdata_external_table_task> on 2023-06-15 15:18:23.800047+00:00
[2023-06-15T15:18:26.166+0000] {standard_task_runner.py:57} INFO - Started process 1000 to run task
[2023-06-15T15:18:26.171+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gcs_2_bq_dag', 'bq_2020_tripdata_external_table_task', 'manual__2023-06-15T15:18:23.800047+00:00', '--job-id', '483', '--raw', '--subdir', 'DAGS_FOLDER/gcs_to_bq.py', '--cfg-path', '/tmp/tmpqarnzzez']
[2023-06-15T15:18:26.174+0000] {standard_task_runner.py:85} INFO - Job 483: Subtask bq_2020_tripdata_external_table_task
[2023-06-15T15:18:26.240+0000] {task_command.py:410} INFO - Running <TaskInstance: gcs_2_bq_dag.bq_2020_tripdata_external_table_task manual__2023-06-15T15:18:23.800047+00:00 [running]> on host 659e337ed365
[2023-06-15T15:18:26.396+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_2_bq_dag' AIRFLOW_CTX_TASK_ID='bq_2020_tripdata_external_table_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T15:18:23.800047+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T15:18:23.800047+00:00'
[2023-06-15T15:18:26.432+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 1606, in execute
    bq_hook = BigQueryHook(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 105, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/google/common/hooks/base_google.py", line 234, in __init__
    self.extras: dict = self.get_connection(self.gcp_conn_id).extra_dejson
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/connection.py", line 434, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `google_cloud_default` isn't defined
[2023-06-15T15:18:26.439+0000] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_2_bq_dag, task_id=bq_2020_tripdata_external_table_task, execution_date=20230615T151823, start_date=20230615T151826, end_date=20230615T151826
[2023-06-15T15:18:26.455+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 483 for task bq_2020_tripdata_external_table_task (The conn_id `google_cloud_default` isn't defined; 1000)
[2023-06-15T15:18:26.503+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T15:18:26.522+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
